export const CREATE_EMAIL = 'CREATE_EMAIL';
export const CREATE_EMAILS_FROM_ARRAY = 'CREATE_EMAILS_FROM_ARRAY';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const DELETE_EMAIL = 'DELETE_EMAIL';
